services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ai-net
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-net
    restart: unless-stopped

volumes:
  jenkins_home:
  ollama_data:

networks:
  ai-net:
    name: ai-net
    driver: bridge